### ISSUE TITLE
polished genomes

### ISSUE THREAD

**Issue by linxingchen** [nanoporetech/DTR-phage-pipeline#2]
Hi,

Could you please let me know if you have other polished genomes excepting the uvMED ones, for example, any genomes polished from the three samples (25 m, 117 m, and 250 m).

Thanks in advance.

Lin-Xing Chen
postdoc in The Banfield Lab

**Comment by jbeaulaurier** [comment]
Hi Lin-Xing,

All the polished genomes from the three samples (25 m, 117 m, and 250 m) can be found in the [assembly](https://www.ncbi.nlm.nih.gov/assembly?LinkName=bioproject_assembly_all&from_uid=529454) section of the Bioproject PRJNA529454. Does that answer your question?

Thanks,
John Beaulaurier

**Comment by linxingchen** [comment]
> Hi Lin-Xing,
> 
> All the polished genomes from the three samples (25 m, 117 m, and 250 m) can be found in the [assembly](https://www.ncbi.nlm.nih.gov/assembly?LinkName=bioproject_assembly_all&from_uid=529454) section of the Bioproject PRJNA529454. Does that answer your question?
> 
> Thanks,
> John Beaulaurier

Hi John,

Thank you so much for your quick reply. It is exactly what I am looking for.

Best,
Lin-Xing
