### ISSUE TITLE
job execution failed

### ISSUE THREAD

**Issue by snayfach** [nanoporetech/DTR-phage-pipeline#8]
Hello and thanks for the promising tool. I've install the pipeline and am trying to run the example using: `snakemake --use-conda --conda-frontend mamba -p -r -j 10`

Here's the error I'm getting (with the full log attached):

> Traceback (most recent call last):
>   File "/global/homes/s/snayfach/.conda/envs/iontorrent/lib/python3.6/site-packages/snakemake/__init__.py", line 778, in snakemake
>     executesubworkflows=execute_subworkflows,
>   File "/global/homes/s/snayfach/.conda/envs/iontorrent/lib/python3.6/site-packages/snakemake/workflow.py", line 701, in execute
>     dag.update_checkpoint_dependencies()
>   File "/global/homes/s/snayfach/.conda/envs/iontorrent/lib/python3.6/site-packages/snakemake/dag.py", line 1296, in update_checkpoint_dependencies
>     logger.info("Updating job {} ({}).".format(self.jobid(j), j))
>   File "/global/homes/s/snayfach/.conda/envs/iontorrent/lib/python3.6/site-packages/snakemake/dag.py", line 702, in jobid
>     return self._jobid[job]
> KeyError: align_dtr_seqs_to_polished_refs
> [Tue Dec 22 13:13:19 2020]
> Finished job 23.
> 137 of 147 steps (93%) done
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message
> Complete log: /global/projectb/scratch/snayfach/projects/checkv-db/4_sra/ion_torrent/DTR-phage-pipeline/.snakemake/log/2020-12-22T130253.555676.snakemake.log

[log.txt](https://github.com/nanoporetech/DTR-phage-pipeline/files/5732068/log.txt)

**Comment by jmeppley** [comment]
Hi, Stephen,

That is a snakemake bug that I'm hoping will be fixed soon. In the test
case at least, simply running snakemake again finishes the workflow.

-John

**Comment by snayfach** [comment]
Hi John. Thanks for the quick reply and solution to my problem! Feel free to leave open or close as you prefer.

**Comment by jmeppley** [comment]
So, it worked for you to run it again?
